server:
  port: 8082
  servlet:
    context-path: /crudService

spring:
  application:
    name: crudService
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://sql10.freesqldatabase.com:3306/sql10440803?useTimezone=true&serverTimezone=UTC
    username: sql10440803
    password: wS5EeMB4Ap
